// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file easydds.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__EASYDDS_HPP
#define FAST_DDS_GENERATED__EASYDDS_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(EASYDDS_SOURCE)
#define EASYDDS_DllAPI __declspec( dllexport )
#else
#define EASYDDS_DllAPI __declspec( dllimport )
#endif // EASYDDS_SOURCE
#else
#define EASYDDS_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define EASYDDS_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure Employee defined by the user in the IDL file.
 * @ingroup easydds
 */
class Employee
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Employee()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Employee()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Employee that will be copied.
     */
    eProsima_user_DllExport Employee(
            const Employee& x)
    {
                    m_text = x.m_text;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Employee that will be copied.
     */
    eProsima_user_DllExport Employee(
            Employee&& x) noexcept
    {
        m_text = std::move(x.m_text);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Employee that will be copied.
     */
    eProsima_user_DllExport Employee& operator =(
            const Employee& x)
    {

                    m_text = x.m_text;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Employee that will be copied.
     */
    eProsima_user_DllExport Employee& operator =(
            Employee&& x) noexcept
    {

        m_text = std::move(x.m_text);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Employee object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Employee& x) const
    {
        return (m_text == x.m_text);
    }

    /*!
     * @brief Comparison operator.
     * @param x Employee object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Employee& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member text
     * @param _text New value to be copied in member text
     */
    eProsima_user_DllExport void text(
            const std::string& _text)
    {
        m_text = _text;
    }

    /*!
     * @brief This function moves the value in member text
     * @param _text New value to be moved in member text
     */
    eProsima_user_DllExport void text(
            std::string&& _text)
    {
        m_text = std::move(_text);
    }

    /*!
     * @brief This function returns a constant reference to member text
     * @return Constant reference to member text
     */
    eProsima_user_DllExport const std::string& text() const
    {
        return m_text;
    }

    /*!
     * @brief This function returns a reference to member text
     * @return Reference to member text
     */
    eProsima_user_DllExport std::string& text()
    {
        return m_text;
    }



private:

    std::string m_text;

};

#endif // _FAST_DDS_GENERATED_EASYDDS_HPP_


