// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file easyddsTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "easyddsTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "easydds.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_Employee_type_identifier(
        TypeIdentifierPair& type_ids_Employee)
{

    ReturnCode_t return_code_Employee {eprosima::fastdds::dds::RETCODE_OK};
    return_code_Employee =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Employee", type_ids_Employee);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_Employee)
    {
        StructTypeFlag struct_flags_Employee = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_Employee = "Employee";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_Employee;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_Employee;
        CompleteTypeDetail detail_Employee = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_Employee, ann_custom_Employee, type_name_Employee.to_string());
        CompleteStructHeader header_Employee;
        header_Employee = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_Employee);
        CompleteStructMemberSeq member_seq_Employee;
        {
            TypeIdentifierPair type_ids_text;
            ReturnCode_t return_code_text {eprosima::fastdds::dds::RETCODE_OK};
            return_code_text =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_text);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_text)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_text))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_text = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_text = 0x00000000;
            bool common_text_ec {false};
            CommonStructMember common_text {TypeObjectUtils::build_common_struct_member(member_id_text, member_flags_text, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_text, common_text_ec))};
            if (!common_text_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure text member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_text = "text";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_text;
            ann_custom_Employee.reset();
            CompleteMemberDetail detail_text = TypeObjectUtils::build_complete_member_detail(name_text, member_ann_builtin_text, ann_custom_Employee);
            CompleteStructMember member_text = TypeObjectUtils::build_complete_struct_member(common_text, detail_text);
            TypeObjectUtils::add_complete_struct_member(member_seq_Employee, member_text);
        }
        CompleteStructType struct_type_Employee = TypeObjectUtils::build_complete_struct_type(struct_flags_Employee, header_Employee, member_seq_Employee);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_Employee, type_name_Employee.to_string(), type_ids_Employee))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Employee already registered in TypeObjectRegistry for a different type.");
        }
    }
}

