// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file easyddsMonitorSub.cxx
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastddsgen.
 */

#include "easyddsMonitorSub.hpp"
#include "dataTrans.hpp"

#include <condition_variable>
#include <stdexcept>

#include <fastdds/dds/core/status/SubscriptionMatchedStatus.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
#include <fastdds/dds/subscriber/qos/SubscriberQos.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>

#include <fastdds/statistics/topic_names.hpp>
#include <fastdds/statistics/dds/subscriber/qos/DataReaderQos.hpp>
#include <fastdds/statistics/types/types.hpp>
#include <fastdds/statistics/types/typesPubSubTypes.hpp>

using namespace eprosima::fastdds::dds;

easyddsMonitorSub::easyddsMonitorSub(
        const int& domain_id
        , const std::string& topic_name)
    : m_topicName(topic_name)
    , factory_(nullptr)
    , participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , reader_(nullptr)
    // , type_(new EmployeePubSubType())
    , samples_received_(0)
    , stop_(false)
{
    // Create the participant
    DomainParticipantQos pqos = PARTICIPANT_QOS_DEFAULT;
    // pqos.name("easydds_monitor_participant");
    /* Previous string conversion is needed for string_255 */
    std::string participant_name = "monitor_domain_" + std::to_string(domain_id);
    pqos.name(participant_name);

    // pqos.properties().properties().emplace_back(
    //     "fastdds.application.id",
    //     "0",
    //     "true");
    // pqos.properties().properties().emplace_back(
    //     "fastdds.application.metadata",
    //     "",
    //     "true");

    factory_ = DomainParticipantFactory::get_shared_instance();
    participant_ = factory_->create_participant(domain_id, pqos, nullptr, StatusMask::none());
    if (participant_ == nullptr)
    {
        throw std::runtime_error("Employee Participant initialization failed");
    }

    if("SENT_DATA_TOPIC" == topic_name)
    {
        type_ = TypeSupport(new statistics::SentDataPubSubType());
    }
    else if("HISTORY_LATENCY_TOPIC" == topic_name)
    {
        type_ = TypeSupport(new statistics::WriterReaderDataPubSubType());
    }
    else
    {
        type_ = TypeSupport(new statistics::ReceivedDataPubSubType());
    }

    // Register the type
    participant_->register_type(type_, type_.get_type_name());

    // Create the subscriber
    subscriber_ = participant_->create_subscriber(SUBSCRIBER_QOS_DEFAULT, nullptr, StatusMask::none());
    if (subscriber_ == nullptr)
    {
        throw std::runtime_error("Employee Subscriber initialization failed");
    }

    std::string sub_topic_name = statistics::SENT_DATA_TOPIC;
    if("RECEIVED_DATA_TOPIC" == topic_name)
    {
        sub_topic_name = statistics::RECEIVED_DATA_TOPIC;
    }
    else if("HISTORY_LATENCY_TOPIC" == topic_name)
    {
        sub_topic_name = statistics::HISTORY_LATENCY_TOPIC;
    }
    // Create the topic
    topic_ = participant_->create_topic(sub_topic_name, type_.get_type_name(), TOPIC_QOS_DEFAULT);
    if (topic_ == nullptr)
    {
        throw std::runtime_error("Employee Topic initialization failed");
    }

    // Create the reader
    DataReaderQos readerQos = statistics::dds::STATISTICS_DATAREADER_QOS;
    reader_ = subscriber_->create_datareader(topic_, readerQos,
                                             this, StatusMask::all());
    if (reader_ == nullptr)
    {
        throw std::runtime_error("Employee DataReader initialization failed");
    }

    std::cout << "create monitor finished" << std::endl;
}

easyddsMonitorSub::~easyddsMonitorSub()
{
    if (nullptr != participant_)
    {
        // Delete DDS entities contained within the DomainParticipant
        participant_->delete_contained_entities();

        // Delete DomainParticipant
        factory_->delete_participant(participant_);
    }
}

void easyddsMonitorSub::on_subscription_matched(
        DataReader* /*reader*/,
        const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        std::cout << "Employee Subscriber matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        std::cout << "Employee Subscriber unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
    }
}

void easyddsMonitorSub::on_data_available(
        DataReader* reader)
{
    if ("SENT_DATA_TOPIC" == m_topicName)
    {
        dealSample<statistics::SentData>(reader, [=](statistics::SentData sample_){
            auto result = deserialize_sample_identity(sample_.sample_id());
            std::cout << "SentData sample_identity = " << result.first + "|" + std::to_string(result.second)
                      << ", msg = " << sample_.sent_msg() << std::endl;
        });
    }
    else if ("HISTORY_LATENCY_TOPIC" == m_topicName)
    {
        dealSample<statistics::WriterReaderData>(reader, [=](statistics::WriterReaderData sample_){
            auto readerID = deserialize_guid(sample_.reader_guid());
            auto writerID = deserialize_guid(sample_.writer_guid());
            std::cout << "LATENCY writerID = " << writerID
            << ", readerID = " << readerID << ", latency = " << sample_.data() << std::endl; });
    }
    else
    {
        dealSample<statistics::ReceivedData>(reader, [=](statistics::ReceivedData sample_){
            auto result = deserialize_sample_identity(sample_.sample_id());
            auto readerID = deserialize_guid(sample_.reader_guid());
            std::cout << "ReceivedData sample_identity = " << result.first + "|" + std::to_string(result.second)
            << ", readerID = " << readerID << std::endl;
        });
    }
}

void easyddsMonitorSub::run()
{
    std::unique_lock<std::mutex> lck(terminate_cv_mtx_);
    terminate_cv_.wait(lck, [this]
            {
                return is_stopped();
            });
}

bool easyddsMonitorSub::getIsStopped()
{
    return is_stopped();
}

bool easyddsMonitorSub::is_stopped()
{
    return stop_.load();
}

void easyddsMonitorSub::stop()
{
    stop_.store(true);
    terminate_cv_.notify_all();
}